//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otdel_kadrov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<NewWorkers> NewWorkers { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
