//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otdel_kadrov
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewWorkers
    {
        public int ID { get; set; }
        public Nullable<int> People_id { get; set; }
        public Nullable<int> WorkPost_id { get; set; }
        public Nullable<int> Answer_id { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual People People { get; set; }
        public virtual Post Post { get; set; }
    }
}
